name: Ubuntu test python
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v4
      - name: Uruchom Pythona
        env:
          MY_NAME: Jan
        run: |
          python3 print_variable.py
