name: Test secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Show secret
        env:
          MY_SECRET: ${{ secrets.KLUCZ }}
        run: |
          echo "Secret is: $MY_SECRET"
          python3 print_variable.py
