name: Test secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show secret
        env:
          MY_SECRET: ${{ secrets.KLUCZ }}
        run: |
          echo "Secret is: $KLUCZ"
